package com.example.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

enum class ThemeMode(
    val title: String,
    val description: String,
    val primaryAccent: Color,
    val secondaryAccent: Color,
    val tertiaryAccent: Color,
    val surfaceGlass: Color,
    val surfaceGlassLight: Color,
    val borderGlass: Color,
    val backgroundColors: List<Color>,
    val buttonNumberColor: Color,
    val buttonOpColor: Color,
    val buttonFuncColor: Color,
    val buttonActionColor: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val isLight: Boolean = false
) {
    LIGHT(
        title = "Light",
        description = "Minimal off-white canvas with radiant warm orange highlights",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(
            Color(0xFFF8F7F5),
            Color(0xFFFAF9F6),
            Color(0xFFF3F1EC)
        ),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),

    DARK(
        title = "Dark",
        description = "Deep obsidian matte canvas with sleek dark glass & vibrant orange",
        primaryAccent = Color(0xFFFF8A00),
        secondaryAccent = Color(0xFFFFA02E),
        tertiaryAccent = Color(0xFFFF6230),
        surfaceGlass = Color(0xCC202024),
        surfaceGlassLight = Color(0xEE2A2A30),
        borderGlass = Color(0x2EFFFFFF),
        backgroundColors = listOf(
            Color(0xFF121214),
            Color(0xFF18181B),
            Color(0xFF0F0F11)
        ),
        buttonNumberColor = Color(0xFF2C2C32),
        buttonOpColor = Color(0x3DFF8A00),
        buttonFuncColor = Color(0xFF383840),
        buttonActionColor = Color(0xFFFF8A00),
        textPrimary = Color(0xFFFFFFFF),
        textSecondary = Color(0xFFA1A1AA),
        isLight = false
    ),

    CYBER_NEON(
        title = "Cyber Neon",
        description = "Cyberpunk matrix canvas with glowing neon cyan & vivid magenta",
        primaryAccent = Color(0xFF00F5D4),
        secondaryAccent = Color(0xFFD946EF),
        tertiaryAccent = Color(0xFF38BDF8),
        surfaceGlass = Color(0xD9121626),
        surfaceGlassLight = Color(0xEE1E243D),
        borderGlass = Color(0x6600F5D4),
        backgroundColors = listOf(
            Color(0xFF090A12),
            Color(0xFF101322),
            Color(0xFF0C0916)
        ),
        buttonNumberColor = Color(0xCC1A1F36),
        buttonOpColor = Color(0x3800F5D4),
        buttonFuncColor = Color(0x38D946EF),
        buttonActionColor = Color(0xFF00F5D4),
        textPrimary = Color(0xFFFFFFFF),
        textSecondary = Color(0xFF94A3B8),
        isLight = false
    ),

    NORDIC(
        title = "Nordic",
        description = "Clean Scandinavian fjord mist with arctic slate & cool ocean blue",
        primaryAccent = Color(0xFF2563EB),
        secondaryAccent = Color(0xFF38BDF8),
        tertiaryAccent = Color(0xFF0D9488),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x1A1E293B),
        backgroundColors = listOf(
            Color(0xFFF1F5F9),
            Color(0xFFE2E8F0),
            Color(0xFFF8FAFC)
        ),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFE0EDFF),
        buttonFuncColor = Color(0xFFF1F5F9),
        buttonActionColor = Color(0xFF2563EB),
        textPrimary = Color(0xFF0F172A),
        textSecondary = Color(0xFF64748B),
        isLight = true
    ),

    MIDNIGHT_LIGHT(
        title = "Midnight Light",
        description = "Luminous celestial twilight with deep violet & amethyst lilac",
        primaryAccent = Color(0xFF7C3AED),
        secondaryAccent = Color(0xFFA855F7),
        tertiaryAccent = Color(0xFFEC4899),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x1F7C3AED),
        backgroundColors = listOf(
            Color(0xFFF5F3FF),
            Color(0xFFEDE9FE),
            Color(0xFFFAF5FF)
        ),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFF3E8FF),
        buttonFuncColor = Color(0xFFFAF5FF),
        buttonActionColor = Color(0xFF7C3AED),
        textPrimary = Color(0xFF1E1B4B),
        textSecondary = Color(0xFF6B7280),
        isLight = true
    ),

    // Compatibility aliases
    AURORA(
        title = "Light",
        description = "Default bright minimal theme",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(Color(0xFFF8F7F5), Color(0xFFFAF9F6)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),
    ONE_UI_MINT(
        title = "Light",
        description = "Default bright minimal theme",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(Color(0xFFF8F7F5), Color(0xFFFAF9F6)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),
    ONE_UI_MINT_LIGHT(
        title = "Light",
        description = "Default bright minimal theme",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(Color(0xFFF8F7F5), Color(0xFFFAF9F6)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),
    IOS_DARK(
        title = "Dark",
        description = "Dark obsidian theme",
        primaryAccent = Color(0xFFFF8A00),
        secondaryAccent = Color(0xFFFFA02E),
        tertiaryAccent = Color(0xFFFF6230),
        surfaceGlass = Color(0xCC202024),
        surfaceGlassLight = Color(0xEE2A2A30),
        borderGlass = Color(0x2EFFFFFF),
        backgroundColors = listOf(Color(0xFF121214), Color(0xFF18181B)),
        buttonNumberColor = Color(0xFF2C2C32),
        buttonOpColor = Color(0x3DFF8A00),
        buttonFuncColor = Color(0xFF383840),
        buttonActionColor = Color(0xFFFF8A00),
        textPrimary = Color(0xFFFFFFFF),
        textSecondary = Color(0xFFA1A1AA),
        isLight = false
    ),
    IOS_LIGHT(
        title = "Light",
        description = "Default bright minimal theme",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(Color(0xFFF8F7F5), Color(0xFFFAF9F6)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),
    TITANIUM_DARK(
        title = "Dark",
        description = "Dark obsidian theme",
        primaryAccent = Color(0xFFFF8A00),
        secondaryAccent = Color(0xFFFFA02E),
        tertiaryAccent = Color(0xFFFF6230),
        surfaceGlass = Color(0xCC202024),
        surfaceGlassLight = Color(0xEE2A2A30),
        borderGlass = Color(0x2EFFFFFF),
        backgroundColors = listOf(Color(0xFF121214), Color(0xFF18181B)),
        buttonNumberColor = Color(0xFF2C2C32),
        buttonOpColor = Color(0x3DFF8A00),
        buttonFuncColor = Color(0xFF383840),
        buttonActionColor = Color(0xFFFF8A00),
        textPrimary = Color(0xFFFFFFFF),
        textSecondary = Color(0xFFA1A1AA),
        isLight = false
    ),
    CYBERPUNK_NEON(
        title = "Cyber Neon",
        description = "Neon cyan & magenta",
        primaryAccent = Color(0xFF00F5D4),
        secondaryAccent = Color(0xFFD946EF),
        tertiaryAccent = Color(0xFF38BDF8),
        surfaceGlass = Color(0xD9121626),
        surfaceGlassLight = Color(0xEE1E243D),
        borderGlass = Color(0x6600F5D4),
        backgroundColors = listOf(Color(0xFF090A12), Color(0xFF101322)),
        buttonNumberColor = Color(0xCC1A1F36),
        buttonOpColor = Color(0x3800F5D4),
        buttonFuncColor = Color(0x38D946EF),
        buttonActionColor = Color(0xFF00F5D4),
        textPrimary = Color(0xFFFFFFFF),
        textSecondary = Color(0xFF94A3B8),
        isLight = false
    ),
    SOLAR_FLARE(
        title = "Light",
        description = "Default bright minimal theme",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(Color(0xFFF8F7F5), Color(0xFFFAF9F6)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),
    DEEP_OCEAN(
        title = "Nordic",
        description = "Nordic theme",
        primaryAccent = Color(0xFF2563EB),
        secondaryAccent = Color(0xFF38BDF8),
        tertiaryAccent = Color(0xFF0D9488),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x1A1E293B),
        backgroundColors = listOf(Color(0xFFF1F5F9), Color(0xFFE2E8F0)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFE0EDFF),
        buttonFuncColor = Color(0xFFF1F5F9),
        buttonActionColor = Color(0xFF2563EB),
        textPrimary = Color(0xFF0F172A),
        textSecondary = Color(0xFF64748B),
        isLight = true
    ),
    EMERALD_MINT(
        title = "Light",
        description = "Default bright minimal theme",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(Color(0xFFF8F7F5), Color(0xFFFAF9F6)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),
    ROSE_GOLD(
        title = "Light",
        description = "Default bright minimal theme",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(Color(0xFFF8F7F5), Color(0xFFFAF9F6)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),
    AMOLED_BLACK(
        title = "Dark",
        description = "Dark obsidian theme",
        primaryAccent = Color(0xFFFF8A00),
        secondaryAccent = Color(0xFFFFA02E),
        tertiaryAccent = Color(0xFFFF6230),
        surfaceGlass = Color(0xCC202024),
        surfaceGlassLight = Color(0xEE2A2A30),
        borderGlass = Color(0x2EFFFFFF),
        backgroundColors = listOf(Color(0xFF121214), Color(0xFF18181B)),
        buttonNumberColor = Color(0xFF2C2C32),
        buttonOpColor = Color(0x3DFF8A00),
        buttonFuncColor = Color(0xFF383840),
        buttonActionColor = Color(0xFFFF8A00),
        textPrimary = Color(0xFFFFFFFF),
        textSecondary = Color(0xFFA1A1AA),
        isLight = false
    ),
    FROSTED_GLASS(
        title = "Light",
        description = "Default bright minimal theme",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(Color(0xFFF8F7F5), Color(0xFFFAF9F6)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),
    RETRO_NEO(
        title = "Light",
        description = "Default bright minimal theme",
        primaryAccent = Color(0xFFFF7A00),
        secondaryAccent = Color(0xFFFF9500),
        tertiaryAccent = Color(0xFFFF5E36),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x14000000),
        backgroundColors = listOf(Color(0xFFF8F7F5), Color(0xFFFAF9F6)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFFFEDE0),
        buttonFuncColor = Color(0xFFF4F3F0),
        buttonActionColor = Color(0xFFFF7A00),
        textPrimary = Color(0xFF1C1C1E),
        textSecondary = Color(0xFF8E8E93),
        isLight = true
    ),
    VIOLET_INDIGO(
        title = "Midnight Light",
        description = "Midnight Light theme",
        primaryAccent = Color(0xFF7C3AED),
        secondaryAccent = Color(0xFFA855F7),
        tertiaryAccent = Color(0xFFEC4899),
        surfaceGlass = Color(0xF5FFFFFF),
        surfaceGlassLight = Color(0xFFFFFFFF),
        borderGlass = Color(0x1F7C3AED),
        backgroundColors = listOf(Color(0xFFF5F3FF), Color(0xFFEDE9FE)),
        buttonNumberColor = Color(0xFFFFFFFF),
        buttonOpColor = Color(0xFFF3E8FF),
        buttonFuncColor = Color(0xFFFAF5FF),
        buttonActionColor = Color(0xFF7C3AED),
        textPrimary = Color(0xFF1E1B4B),
        textSecondary = Color(0xFF6B7280),
        isLight = true
    );

    fun getGlassBorderBrush(): Brush {
        return Brush.linearGradient(
            colors = listOf(
                borderGlass.copy(alpha = 0.5f),
                borderGlass.copy(alpha = 0.15f),
                borderGlass.copy(alpha = 0.35f)
            )
        )
    }

    fun getActionGradient(): Brush {
        return Brush.horizontalGradient(
            colors = listOf(primaryAccent, secondaryAccent)
        )
    }

    companion object {
        val selectableThemes = listOf(LIGHT, DARK, CYBER_NEON, NORDIC, MIDNIGHT_LIGHT)
    }
}
